name: ddd_flutter_example
description: Flutter Domain Driven Design Example.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.

publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  uuid: ^2.2.0
  flutter_bloc: ^6.0.1
  get_it: ^4.0.4
  injectable: ^1.0.4
  freezed_annotation: ^0.11.0+1
  flushbar: ^1.10.4

  #Firebase
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.13.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  freezed: ^0.11.5
  injectable_generator: ^1.0.4
  lint: ^1.2.0


flutter:

  uses-material-design: true

  assets:
      - assets/images/
      - assets/logo/
fonts:
  - family: Raleway
    fonts:
      - asset: fonts/raleway/Raleway-Regular.ttf
        weight: 700
      - asset: fonts/raleway/Raleway-Bold.tff
        weight: 700
      - asset: fonts/raleway/Raleway-Italic.ttf
        weight: 300
  - family: RobotoMono
    fonts:
      - asset: fonts/roboto/RobotoMono-Regular.ttf
      - asset: fonts/roboto/RobotoMono-Italic.tff
        weight: 700
      - asset: fonts/roboto/RobotoMono-Bold.ttf
        weight: 700
  

  

